import os
import smtplib
import logging
import re
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import argparse
from datetime import datetime
from dotenv import load_dotenv
from mjml import mjml2html

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def get_args():
    parser = argparse.ArgumentParser(description="Send Reddit Newsletter Email")
    parser.add_argument("--subreddit", type=str, default="triplej", help="Subreddit to send newsletter for")
    return parser.parse_args()

def format_as_html(raw_text, subreddit, digest_type="Daily Digest"):
    """Converts the plain text/markdown summary into a styled HTML newsletter using MJML."""
    
    # 0. Force specific titles to be standard headers so they get centered
    content = re.sub(r'^[\*\s#\-]*?(Newsletter Summary|Mentioned Artists)[\*\s#\-:]*?$', r'### \1', raw_text, flags=re.IGNORECASE | re.MULTILINE)
    
    # 1. Normalize "--- Post 1 ---" or "-- Post 1 --" style dividers into standard headers (removes the dashes)
    content = re.sub(r'^-{2,}\s*(.*?)\s*-{2,}$', r'### \1', content, flags=re.MULTILINE)
    
    # 2. Headers (## or ###) - Centered with elegant styling, force blank lines around them
    content = re.sub(r'^(?:###|##|#)\s+(.*)', r'\n\n<h2 style="color: #222222; text-align: center; margin-top: 40px; margin-bottom: 20px; font-weight: 600; font-size: 22px; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">\1</h2>\n\n', content, flags=re.MULTILINE)
    
    # 3. Bold text
    content = re.sub(r'\*\*(.*?)\*\*', r'<strong style="color: #222222; font-weight: 600;">\1</strong>', content)
    
    # 4. Remove standalone horizontal rules / dashes between posts
    content = re.sub(r'^-{2,}\s*$', '', content, flags=re.MULTILINE)
    
    # 5. List Items (standard native bullets to fix text wrapping)
    content = re.sub(r'^(?:-|\*)\s+(.*)', r'<li style="margin-bottom: 8px; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">\1</li>', content, flags=re.MULTILINE)
    
    # 6. Wrap Lists in <ul> with standard native indentation
    content = re.sub(r'(<li.*?>.*?</li>\n?)+', lambda m: f'\n\n<ul style="margin: 0 0 20px 0; padding-left: 24px; color: #4a4a4a;">\n{m.group(0)}</ul>\n\n', content)
    
    # 7. Normalize excessive newlines
    content = re.sub(r'\n{3,}', '\n\n', content)
    
    # 8. Convert double newlines into clean paragraphs
    paragraphs = content.split('\n\n')
    formatted_paragraphs = []
    for p in paragraphs:
        p = p.strip()
        if not p:
            continue
        
        # If the block is an isolated block element (header, list, hr), just append it
        if p.startswith(('<h', '<ul')):
            formatted_paragraphs.append(p)
        else:
            # Text paragraph, convert single \n to <br> for internal line breaks
            p = p.replace('\n', '<br>')
            formatted_paragraphs.append(f'<p style="margin: 0 0 20px 0; line-height: 1.6; color: #4a4a4a; font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif;">{p}</p>')
            
    html_body = '\n'.join(formatted_paragraphs)

    mjml_template = f"""
    <mjml>
      <mj-head>
        <mj-title>Reddit {digest_type}</mj-title>
        <mj-attributes>
          <mj-all font-family="'Helvetica Neue', Helvetica, Arial, sans-serif" />
        </mj-attributes>
        <mj-style inline="inline">
          .content-wrap {{ box-shadow: 0 4px 15px rgba(0, 0, 0, 0.05); }}
        </mj-style>
      </mj-head>
      <mj-body background-color="#f4f5f7">
        
        <!-- Header Section -->
        <mj-section padding-top="40px" padding-bottom="10px">
          <mj-column>
            <mj-text align="center" color="#ff4500" font-size="34px" font-weight="800" letter-spacing="-1px" padding-bottom="0px">
              r/{subreddit} {digest_type}
            </mj-text>

          </mj-column>
        </mj-section>
        
        <!-- Content Section -->
        <mj-section padding="20px">
          <mj-column background-color="#ffffff" border-radius="12px" padding="30px 20px" css-class="content-wrap">
            <mj-text>
              {html_body}
            </mj-text>
          </mj-column>
        </mj-section>
        
        <!-- Footer Section -->
        <mj-section padding-top="10px" padding-bottom="40px">
          <mj-column>
            <mj-divider border-width="1px" border-color="#eaeaea" width="80%" />
            <mj-text align="center" color="#999999" font-size="13px" line-height="1.5">
              Generated by your Reddit Newsletter Automation.<br/>
              Stay curious!
            </mj-text>
          </mj-column>
        </mj-section>

      </mj-body>
    </mjml>
    """
    
    # Compile MJML into responsive HTML
    result = mjml2html(mjml_template)
    
    # Handle differing return types based on mjml-python versions
    return result['html'] if isinstance(result, dict) else getattr(result, 'html', str(result))

def send_email(html_content, subject="Daily Reddit Newsletter"):
    """Sends the formatted HTML content via email using SMTP."""
    sender = os.getenv("EMAIL_SENDER")
    password = os.getenv("EMAIL_PASSWORD")
    receiver = os.getenv("EMAIL_RECEIVER")
    smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", 587))

    if not all([sender, password, receiver]):
        logger.error("Email configuration missing in .env (EMAIL_SENDER, EMAIL_PASSWORD, EMAIL_RECEIVER).")
        return

    msg = MIMEMultipart()
    msg['From'] = sender
    msg['To'] = receiver
    msg['Subject'] = subject

    # Attach the HTML content
    msg.attach(MIMEText(html_content, 'html'))

    try:
        logger.info(f"Connecting to {smtp_server}:{smtp_port}...")
        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()  # Upgrade to a secure connection
            server.login(sender, password)
            server.send_message(msg)
        logger.info("Email sent successfully!")
    except Exception as e:
        logger.error(f"Failed to send email: {e}")

def main():
    args = get_args()
    subreddit = args.subreddit
    load_dotenv()
    
    current_date = datetime.now().strftime("%Y-%m-%d")
    output_dir = os.path.join("output", subreddit, current_date)
    
    # Path to the generated newsletter summary
    file_path = os.path.join(output_dir, "newsletter_summary.txt")
    
    if not os.path.exists(file_path):
        logger.error(f"Newsletter file not found at: {file_path}")
        return

    logger.info(f"Reading content from {file_path}...")
    with open(file_path, "r", encoding="utf-8") as f:
        raw_text = f.read()

    is_monday = datetime.now().weekday() == 0
    digest_type = "Weekend Digest" if is_monday else "Daily Digest"

    # Wrap the raw OpenAI output in our ideal HTML format
    html_email = format_as_html(raw_text, subreddit, digest_type)
    send_email(html_email, subject=f"Reddit {digest_type}: r/{subreddit} - {current_date}")

if __name__ == "__main__":
    main()
