import os
import smtplib
import logging
import re
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def format_as_html(raw_text):
    """Converts the plain text/markdown summary into a styled HTML newsletter."""
    # Convert Markdown headers (### Title) to <h2> with styling
    content = re.sub(r'^### (.*)', r'<h2 style="color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 5px; margin-top: 25px;">\1</h2>', raw_text, flags=re.MULTILINE)
    
    # Convert bold (**text**) to <strong>
    content = re.sub(r'\*\*(.*?)\*\*', r'<strong style="color: #2c3e50;">\1</strong>', content)
    
    # Convert horizontal rules (---) to <hr>
    content = content.replace('---', '<hr style="border: 0; border-top: 1px solid #ddd; margin: 30px 0;">')
    
    # Convert newlines to <br> for basic spacing
    content = content.replace('\n', '<br>')

    html_template = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #444; margin: 0; padding: 0; }}
            .container {{ max-width: 600px; margin: 20px auto; padding: 25px; border: 1px solid #e1e4e8; border-radius: 12px; background-color: #ffffff; }}
            .header {{ text-align: center; margin-bottom: 30px; border-bottom: 2px solid #ff4500; padding-bottom: 10px; }}
            .footer {{ margin-top: 30px; font-size: 12px; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 15px; }}
        </style>
    </head>
    <body style="background-color: #f6f8fa;">
        <div class="container">
            <div class="header">
                <h1 style="color: #ff4500; margin: 0; font-size: 24px;">Reddit Daily Digest</h1>
            </div>
            {content}
            <div class="footer">
                Generated by your Reddit Newsletter Automation.
            </div>
        </div>
    </body>
    </html>
    """
    return html_template

def send_email(html_content, subject="Daily Reddit Newsletter"):
    """Sends the formatted HTML content via email using SMTP."""
    sender = os.getenv("EMAIL_SENDER")
    password = os.getenv("EMAIL_PASSWORD")
    receiver = os.getenv("EMAIL_RECEIVER")
    smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", 587))

    if not all([sender, password, receiver]):
        logger.error("Email configuration missing in .env (EMAIL_SENDER, EMAIL_PASSWORD, EMAIL_RECEIVER).")
        return

    msg = MIMEMultipart()
    msg['From'] = sender
    msg['To'] = receiver
    msg['Subject'] = subject

    # Attach the HTML content
    msg.attach(MIMEText(html_content, 'html'))

    try:
        logger.info(f"Connecting to {smtp_server}:{smtp_port}...")
        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()  # Upgrade to a secure connection
            server.login(sender, password)
            server.send_message(msg)
        logger.info("Email sent successfully!")
    except Exception as e:
        logger.error(f"Failed to send email: {e}")

def main():
    load_dotenv()
    
    # Path to the generated newsletter summary
    file_path = "newsletter_summary.txt"
    
    if not os.path.exists(file_path):
        logger.error(f"Newsletter file not found at: {file_path}")
        return

    logger.info(f"Reading content from {file_path}...")
    with open(file_path, "r", encoding="utf-8") as f:
        raw_text = f.read()

    # Wrap the raw OpenAI output in our ideal HTML format
    html_email = format_as_html(raw_text)
    send_email(html_email)

if __name__ == "__main__":
    main()
